/**
 * 에러 코드 상수
 *
 * 서비스에서 throw 시 사용. 자동완성 + 오타 방지.
 * 새 에러 추가 시 error-messages.ts에도 메시지 추가 필요.
 */
export const ERROR_CODES = {
  // Factcheck
  EMPTY_TEXT: "EMPTY_TEXT",
  GUEST_LIMIT_EXCEEDED: "GUEST_LIMIT_EXCEEDED",
  FACTCHECK_NOT_FOUND: "FACTCHECK_NOT_FOUND",
  CLAIM_NOT_FOUND: "CLAIM_NOT_FOUND",

  // MCP
  MCP_ERROR: "MCP_ERROR",
  MCP_TIMEOUT: "MCP_TIMEOUT",
  MCP_UNAVAILABLE: "MCP_UNAVAILABLE",

  // Auth
  TOKEN_EXPIRED: "TOKEN_EXPIRED",
  TOKEN_INVALID: "TOKEN_INVALID",
  INVALID_REFRESH_TOKEN: "INVALID_REFRESH_TOKEN",
  USER_NOT_FOUND: "USER_NOT_FOUND",
  INVALID_AUTH_CODE: "INVALID_AUTH_CODE",
  GUEST_NOT_ALLOWED: "GUEST_NOT_ALLOWED",

  // Settings
  DUPLICATE_DOMAIN: "DUPLICATE_DOMAIN",
  DOMAIN_CONFLICT: "DOMAIN_CONFLICT",
  INVALID_DOMAIN: "INVALID_DOMAIN",

  // Validation
  VALIDATION_ERROR: "VALIDATION_ERROR",

  // 기본
  INTERNAL_SERVER_ERROR: "INTERNAL_SERVER_ERROR",
  BAD_REQUEST: "BAD_REQUEST",
} as const;

export type ErrorCode = (typeof ERROR_CODES)[keyof typeof ERROR_CODES];
