const REFRESH_EXPIRES_DAYS = 7;

export const JWT_EXPIRES = {
  ACCESS: "1h",
  REFRESH: `${REFRESH_EXPIRES_DAYS}d`,
  GUEST: `${REFRESH_EXPIRES_DAYS}d`,
} as const;

export const REFRESH_TOKEN_TTL_MS = REFRESH_EXPIRES_DAYS * 24 * 60 * 60 * 1000;

export const GUEST_CONFIG = {
  INITIAL_USES: 3,
  TTL_SECONDS: REFRESH_EXPIRES_DAYS * 24 * 60 * 60,
} as const;

export const CODE_EXPIRES_MS = 60 * 60 * 1000;
